function normalizeCatalogText(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
}

const baseExerciseLibrary = [
  { name: 'Supino reto com barra', group: 'Peitoral', equipment: 'Barra e banco', cues: 'Pés firmes, escápulas apoiadas e barra descendo com controle até a linha média do peito.', aliases: ['supino reto', 'bench press'] },
  { name: 'Supino inclinado com halteres', group: 'Peitoral', equipment: 'Halteres e banco', cues: 'Mantenha o peito aberto, antebraços alinhados e evite perder a posição dos ombros.', aliases: ['supino inclinado'] },
  { name: 'Crucifixo com halteres', group: 'Peitoral', equipment: 'Halteres e banco', cues: 'Cotovelos levemente flexionados e amplitude controlada sem forçar a articulação do ombro.', aliases: ['crucifixo'] },
  { name: 'Flexão de braços', group: 'Peitoral', equipment: 'Peso corporal', cues: 'Corpo alinhado, abdômen ativo e cotovelos acompanhando a linha natural dos ombros.', aliases: ['flexao', 'flexão'] },
  { name: 'Puxada frontal', group: 'Costas', equipment: 'Polia alta', cues: 'Inicie deprimindo as escápulas e puxe a barra em direção à parte superior do peito.', aliases: ['puxada alta', 'pulley frente'] },
  { name: 'Remada baixa', group: 'Costas', equipment: 'Polia baixa', cues: 'Tronco estável, peito aberto e cotovelos conduzindo o movimento para trás.', aliases: ['remada sentada'] },
  { name: 'Remada curvada com barra', group: 'Costas', equipment: 'Barra', cues: 'Quadril para trás, coluna neutra e barra aproximando-se do abdômen sem balanço.', aliases: ['remada curvada'] },
  { name: 'Barra fixa', group: 'Costas', equipment: 'Barra fixa', cues: 'Evite impulso, mantenha o tronco firme e conduza o peito em direção à barra.', aliases: ['pull up', 'barra'] },
  { name: 'Desenvolvimento com halteres', group: 'Ombros', equipment: 'Halteres', cues: 'Abdômen ativo, punhos alinhados e subida sem compensar com a lombar.', aliases: ['desenvolvimento', 'shoulder press'] },
  { name: 'Elevação lateral', group: 'Ombros', equipment: 'Halteres', cues: 'Eleve pelos cotovelos até a linha dos ombros, sem embalo e com carga controlada.', aliases: ['elevacao lateral'] },
  { name: 'Rosca direta', group: 'Bíceps', equipment: 'Barra', cues: 'Cotovelos próximos ao tronco e movimento sem inclinar o corpo para gerar impulso.', aliases: ['rosca barra'] },
  { name: 'Rosca alternada', group: 'Bíceps', equipment: 'Halteres', cues: 'Mantenha o braço estável e controle completamente a fase de descida.', aliases: ['rosca com halteres'] },
  { name: 'Tríceps na polia', group: 'Tríceps', equipment: 'Polia', cues: 'Cotovelos fixos, ombros baixos e extensão completa sem movimentar o tronco.', aliases: ['triceps pulley', 'tríceps pulley'] },
  { name: 'Tríceps francês', group: 'Tríceps', equipment: 'Halter', cues: 'Mantenha os cotovelos apontados à frente e evite compensação lombar.', aliases: ['triceps frances'] },
  { name: 'Agachamento livre', group: 'Quadríceps e glúteos', equipment: 'Barra', cues: 'Pés firmes, joelhos acompanhando a direção dos pés e coluna neutra durante toda a amplitude.', aliases: ['agachamento', 'back squat'] },
  { name: 'Leg press 45°', group: 'Quadríceps e glúteos', equipment: 'Leg press', cues: 'Lombar apoiada, joelhos alinhados e descida apenas até manter a pelve estável.', aliases: ['leg press'] },
  { name: 'Cadeira extensora', group: 'Quadríceps', equipment: 'Máquina', cues: 'Ajuste o eixo ao joelho, estabilize o quadril e controle a descida.', aliases: ['extensora'] },
  { name: 'Mesa flexora', group: 'Posteriores de coxa', equipment: 'Máquina', cues: 'Quadril apoiado, abdômen ativo e flexão sem tirar o tronco do banco.', aliases: ['flexora deitada'] },
  { name: 'Stiff com barra', group: 'Posteriores e glúteos', equipment: 'Barra', cues: 'Empurre o quadril para trás, mantenha a barra próxima às pernas e preserve a coluna neutra.', aliases: ['stiff', 'romeno'] },
  { name: 'Levantamento terra', group: 'Posteriores e costas', equipment: 'Barra', cues: 'Barra próxima ao corpo, tronco firme e força aplicada pelo chão sem arredondar a coluna.', aliases: ['terra', 'deadlift'] },
  { name: 'Afundo com halteres', group: 'Quadríceps e glúteos', equipment: 'Halteres', cues: 'Passo estável, tronco organizado e joelho dianteiro acompanhando a ponta do pé.', aliases: ['afundo', 'passada'] },
  { name: 'Elevação pélvica', group: 'Glúteos', equipment: 'Banco e barra', cues: 'Queixo levemente recolhido, costelas baixas e extensão do quadril sem hiperestender a lombar.', aliases: ['hip thrust'] },
  { name: 'Panturrilha em pé', group: 'Panturrilhas', equipment: 'Máquina ou peso corporal', cues: 'Use amplitude completa, pause no topo e controle a descida sem quicar.', aliases: ['panturrilha'] },
  { name: 'Prancha abdominal', group: 'Core', equipment: 'Peso corporal', cues: 'Contraia glúteos e abdômen, mantendo cabeça, tronco e quadril alinhados.', aliases: ['prancha'] },
  { name: 'Abdominal crunch', group: 'Core', equipment: 'Peso corporal', cues: 'Aproxime costelas e pelve sem puxar a cabeça e retorne de forma controlada.', aliases: ['abdominal'] },
]

const exerciseCatalogBlueprints = [
  {
    base: 'Supino',
    english: ['bench press', 'press'],
    group: 'Peitoral',
    primaryMuscle: 'peitoral',
    secondaryMuscles: ['deltoide-anterior', 'triceps'],
    movementType: 'Empurrar horizontal',
    objective: 'Hipertrofia e força',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Intermediário',
    difficulty: 'Média',
    laterality: 'Bilateral',
    variants: ['reto', 'inclinado', 'declinado', 'fechado'],
    equipments: ['Barra', 'Halteres', 'Smith', 'Máquina'],
    instruction: 'Mantenha escápulas firmes, pés apoiados e controle a descida antes de empurrar.',
    tip: 'Priorize trajetória estável e punhos alinhados aos cotovelos.',
    mistake: 'Perder a posição das escápulas ou quicar a carga no peito.',
  },
  {
    base: 'Crucifixo',
    english: ['fly', 'chest fly'],
    group: 'Peitoral',
    primaryMuscle: 'peitoral',
    secondaryMuscles: ['deltoide-anterior'],
    movementType: 'Adução horizontal',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['reto', 'inclinado', 'declinado'],
    equipments: ['Halteres', 'Cabos', 'Máquina'],
    instruction: 'Abra os braços com cotovelos levemente flexionados e retorne contraindo o peitoral.',
    tip: 'Controle a amplitude para não sobrecarregar o ombro.',
    mistake: 'Transformar o movimento em supino dobrando demais os cotovelos.',
  },
  {
    base: 'Puxada',
    english: ['lat pulldown', 'pulldown'],
    group: 'Costas',
    primaryMuscle: 'dorsal',
    secondaryMuscles: ['costas', 'biceps'],
    movementType: 'Puxar vertical',
    objective: 'Hipertrofia e postura',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['frontal', 'pegada aberta', 'pegada neutra', 'unilateral'],
    equipments: ['Polia alta', 'Máquina', 'Elástico'],
    instruction: 'Inicie com as escápulas baixas e puxe os cotovelos em direção ao tronco.',
    tip: 'Pense em puxar com os cotovelos, não com as mãos.',
    mistake: 'Inclinar demais o tronco e perder tensão nas dorsais.',
  },
  {
    base: 'Remada',
    english: ['row', 'seated row'],
    group: 'Costas',
    primaryMuscle: 'costas',
    secondaryMuscles: ['dorsal', 'biceps', 'deltoide-posterior'],
    movementType: 'Puxar horizontal',
    objective: 'Hipertrofia e força',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Intermediário',
    difficulty: 'Média',
    laterality: 'Bilateral',
    variants: ['baixa', 'curvada', 'serrote', 'cavalinho', 'alta'],
    equipments: ['Barra', 'Halteres', 'Polia baixa', 'Máquina', 'Smith', 'TRX'],
    instruction: 'Mantenha tronco firme, peito aberto e conduza o movimento pelos cotovelos.',
    tip: 'Pause brevemente com escápulas contraídas.',
    mistake: 'Usar balanço de tronco para completar a repetição.',
  },
  {
    base: 'Desenvolvimento',
    english: ['shoulder press', 'overhead press'],
    group: 'Ombros',
    primaryMuscle: 'deltoide-anterior',
    secondaryMuscles: ['deltoide-lateral', 'triceps'],
    movementType: 'Empurrar vertical',
    objective: 'Força e hipertrofia',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Intermediário',
    difficulty: 'Média',
    laterality: 'Bilateral',
    variants: ['sentado', 'em pé', 'unilateral', 'arnold'],
    equipments: ['Halteres', 'Barra', 'Máquina', 'Smith', 'Kettlebell'],
    instruction: 'Suba a carga acima da cabeça mantendo abdômen firme e punhos alinhados.',
    tip: 'Evite arquear a lombar no final da subida.',
    mistake: 'Compensar com tronco ou perder alinhamento dos cotovelos.',
  },
  {
    base: 'Elevação',
    english: ['raise', 'lateral raise', 'front raise'],
    group: 'Ombros',
    primaryMuscle: 'deltoide-lateral',
    secondaryMuscles: ['deltoide-anterior', 'trapezio'],
    movementType: 'Abdução de ombro',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['lateral', 'frontal', 'posterior', 'unilateral'],
    equipments: ['Halteres', 'Cabos', 'Máquina', 'Elástico'],
    instruction: 'Eleve com controle até a linha dos ombros sem usar impulso.',
    tip: 'Conduza o movimento pelos cotovelos.',
    mistake: 'Subir a carga com trapézio ou balançar o corpo.',
  },
  {
    base: 'Rosca',
    english: ['curl', 'biceps curl'],
    group: 'Bíceps',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebraco'],
    movementType: 'Flexão de cotovelo',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['direta', 'alternada', 'martelo', 'scott', 'concentrada', 'inclinada'],
    equipments: ['Barra', 'Halteres', 'Cabos', 'Máquina', 'Elástico'],
    instruction: 'Flexione o cotovelo sem projetar o ombro para frente e controle a descida.',
    tip: 'Mantenha cotovelos estáveis e punhos neutros.',
    mistake: 'Usar balanço do tronco para levantar a carga.',
  },
  {
    base: 'Tríceps',
    english: ['triceps extension', 'pushdown'],
    group: 'Tríceps',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['antebraco'],
    movementType: 'Extensão de cotovelo',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['corda', 'barra reta', 'francês', 'testa', 'coice', 'unilateral'],
    equipments: ['Polia', 'Halteres', 'Barra', 'Elástico'],
    instruction: 'Fixe os cotovelos e estenda completamente sem movimentar o tronco.',
    tip: 'Controle o retorno para manter tensão no tríceps.',
    mistake: 'Abrir cotovelos ou usar ombros para ajudar.',
  },
  {
    base: 'Agachamento',
    english: ['squat'],
    group: 'Quadríceps',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: ['gluteos', 'adutores', 'posterior-coxa'],
    movementType: 'Agachar',
    objective: 'Força, hipertrofia e performance',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Intermediário',
    difficulty: 'Média',
    laterality: 'Bilateral',
    variants: ['livre', 'frontal', 'sumô', 'goblet', 'búlgaro', 'hack'],
    equipments: ['Barra', 'Halteres', 'Smith', 'Máquina', 'Kettlebell', 'Peso corporal'],
    instruction: 'Desça com controle, joelhos alinhados aos pés e tronco firme.',
    tip: 'Mantenha pressão no pé inteiro durante a subida.',
    mistake: 'Fechar os joelhos para dentro ou perder a coluna neutra.',
  },
  {
    base: 'Leg press',
    english: ['leg press'],
    group: 'Quadríceps',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: ['gluteos', 'adutores'],
    movementType: 'Empurrar com pernas',
    objective: 'Hipertrofia',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['45°', 'horizontal', 'unilateral', 'pés altos', 'pés baixos'],
    equipments: ['Máquina', 'Leg press'],
    instruction: 'Mantenha quadril apoiado e desça até onde a lombar permanece estável.',
    tip: 'Ajuste a posição dos pés conforme o foco do treino.',
    mistake: 'Descer demais e arredondar a lombar.',
  },
  {
    base: 'Cadeira',
    english: ['leg machine'],
    group: 'Quadríceps',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: [],
    movementType: 'Extensão de joelho',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['extensora', 'extensora unilateral'],
    equipments: ['Máquina'],
    instruction: 'Ajuste o eixo ao joelho e controle a fase de descida.',
    tip: 'Segure um segundo no topo para melhorar a contração.',
    mistake: 'Usar impulso e perder controle do joelho.',
  },
  {
    base: 'Flexora',
    english: ['leg curl', 'hamstring curl'],
    group: 'Posteriores de coxa',
    primaryMuscle: 'posterior-coxa',
    secondaryMuscles: ['panturrilhas'],
    movementType: 'Flexão de joelho',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['deitada', 'sentada', 'em pé', 'unilateral'],
    equipments: ['Máquina', 'Elástico'],
    instruction: 'Flexione o joelho sem tirar o quadril do apoio e controle o retorno.',
    tip: 'Evite acelerar a descida.',
    mistake: 'Levantar o quadril ou reduzir a amplitude.',
  },
  {
    base: 'Stiff',
    english: ['romanian deadlift', 'rdl'],
    group: 'Posteriores de coxa',
    primaryMuscle: 'posterior-coxa',
    secondaryMuscles: ['gluteos', 'lombar'],
    movementType: 'Hinge de quadril',
    objective: 'Força e hipertrofia',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Intermediário',
    difficulty: 'Média',
    laterality: 'Bilateral',
    variants: ['tradicional', 'romeno', 'unilateral', 'sumô'],
    equipments: ['Barra', 'Halteres', 'Smith', 'Kettlebell'],
    instruction: 'Empurre o quadril para trás e mantenha a carga próxima às pernas.',
    tip: 'Sinta alongar posterior sem arredondar a coluna.',
    mistake: 'Buscar amplitude sacrificando a lombar.',
  },
  {
    base: 'Elevação pélvica',
    english: ['hip thrust', 'glute bridge'],
    group: 'Glúteos',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['posterior-coxa'],
    movementType: 'Extensão de quadril',
    objective: 'Hipertrofia de glúteos',
    mechanic: 'Composto',
    composition: 'Composto',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['com barra', 'unilateral', 'no banco', 'no solo', 'com pausa'],
    equipments: ['Barra', 'Halteres', 'Máquina', 'Elástico', 'Peso corporal'],
    instruction: 'Suba o quadril contraindo glúteos e evitando hiperextensão lombar.',
    tip: 'Faça retroversão pélvica leve no topo.',
    mistake: 'Finalizar com lombar em vez de glúteos.',
  },
  {
    base: 'Panturrilha',
    english: ['calf raise'],
    group: 'Panturrilhas',
    primaryMuscle: 'panturrilhas',
    secondaryMuscles: [],
    movementType: 'Flexão plantar',
    objective: 'Hipertrofia',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['em pé', 'sentado', 'no leg press', 'unilateral'],
    equipments: ['Máquina', 'Leg press', 'Halteres', 'Smith', 'Peso corporal'],
    instruction: 'Use amplitude completa, pause no topo e controle a descida.',
    tip: 'Evite quicar no final da repetição.',
    mistake: 'Fazer repetições curtas e rápidas demais.',
  },
  {
    base: 'Abdominal',
    english: ['abs', 'crunch'],
    group: 'Core',
    primaryMuscle: 'abdomen',
    secondaryMuscles: ['obliquos'],
    movementType: 'Flexão/estabilização de tronco',
    objective: 'Core e estabilidade',
    mechanic: 'Isolado',
    composition: 'Isolado',
    level: 'Iniciante',
    difficulty: 'Baixa',
    laterality: 'Bilateral',
    variants: ['crunch', 'infra', 'bicicleta', 'na polia', 'canivete', 'prancha'],
    equipments: ['Peso corporal', 'Polia', 'Máquina', 'Bola suíça'],
    instruction: 'Controle tronco e respiração sem puxar o pescoço.',
    tip: 'Aproxime costelas e pelve com controle.',
    mistake: 'Compensar com pescoço ou lombar.',
  },
]

export function buildExpandedExerciseCatalog() {
  const records = []
  const existingNames = new Set(baseExerciseLibrary.map((exercise) => normalizeCatalogText(exercise.name)))

  exerciseCatalogBlueprints.forEach((blueprint) => {
    blueprint.variants.forEach((variant) => {
      blueprint.equipments.forEach((equipment) => {
        const lowerVariant = normalizeCatalogText(variant)
        const lowerEquipment = normalizeCatalogText(equipment)
        const suffix = lowerEquipment.includes('peso corporal') ? '' : ` com ${equipment.toLowerCase()}`
        const name = `${blueprint.base} ${variant}${suffix}`.replace(/\s+/g, ' ').trim()
        const key = normalizeCatalogText(name)
        if (existingNames.has(key)) return
        existingNames.add(key)
        records.push({
          name,
          group: blueprint.group,
          muscleGroup: blueprint.group,
          primaryMuscle: blueprint.primaryMuscle,
          secondaryMuscles: blueprint.secondaryMuscles,
          equipment,
          category: blueprint.objective,
          movementType: blueprint.movementType,
          movement: blueprint.movementType,
          objective: blueprint.objective,
          level: blueprint.level,
          mechanic: blueprint.mechanic,
          mechanics: blueprint.mechanic,
          laterality: lowerVariant.includes('unilateral') ? 'Unilateral' : blueprint.laterality,
          composition: blueprint.composition,
          difficulty: blueprint.difficulty,
          cues: blueprint.instruction,
          instructions: blueprint.instruction,
          tips: blueprint.tip,
          commonMistakes: blueprint.mistake,
          source: 'coachfit_catalog',
          aliases: [
            blueprint.base,
            variant,
            equipment,
            `${blueprint.base} ${variant}`,
            ...blueprint.english,
            ...blueprint.english.map((item) => `${item} ${variant}`),
          ],
        })
      })
    })
  })

  return records
}

export const exerciseLibrary = [...baseExerciseLibrary, ...buildExpandedExerciseCatalog()]
