begin;

-- Preserve server-side attribution from invite -> checkout -> payment.
alter table public.student_checkout_sessions
  add column if not exists source_invite_id uuid references public.student_invites(id) on delete set null,
  add column if not exists affiliate_email_snapshot text,
  add column if not exists professional_type_snapshot text,
  add column if not exists offer_code text,
  add column if not exists last_provider_event_at timestamptz,
  add column if not exists last_provider_event_id text,
  add column if not exists last_provider_event_rank integer not null default 0;

alter table public.student_checkout_sessions
  drop constraint if exists student_checkout_sessions_professional_type_snapshot_check;

alter table public.student_checkout_sessions
  add constraint student_checkout_sessions_professional_type_snapshot_check
  check (
    professional_type_snapshot is null
    or professional_type_snapshot in ('trainer', 'nutritionist')
  );

alter table public.payment_webhook_events
  add column if not exists provider_event_at timestamptz;

-- Prevent future duplicate students by normalized e-mail. Production was audited
-- before this migration and had no duplicate e-mail group per professional.
create unique index if not exists students_coach_normalized_email_unique
  on public.students (coach_id, lower(btrim(email)))
  where coach_id is not null and email is not null and btrim(email) <> '';

-- Existing production has historical phone duplicates. Do not mutate them.
-- Only reject a NEW/CHANGED phone that would create another duplicate.
create or replace function public.coachfit_reject_new_duplicate_student_phone()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_phone text;
  v_old_phone text;
begin
  v_phone := regexp_replace(coalesce(new.phone, ''), '\\D', '', 'g');

  if tg_op = 'UPDATE' then
    v_old_phone := regexp_replace(coalesce(old.phone, ''), '\\D', '', 'g');
    if new.coach_id is not distinct from old.coach_id
       and v_phone is not distinct from v_old_phone then
      return new;
    end if;
  end if;

  if new.coach_id is not null and v_phone <> '' and exists (
    select 1
    from public.students as students
    where students.coach_id = new.coach_id
      and students.id is distinct from new.id
      and regexp_replace(coalesce(students.phone, ''), '\\D', '', 'g') = v_phone
  ) then
    raise exception 'Ja existe aluno/paciente deste profissional com este telefone.'
      using errcode = '23505';
  end if;

  return new;
end;
$$;

revoke all on function public.coachfit_reject_new_duplicate_student_phone() from public, anon, authenticated;

drop trigger if exists coachfit_reject_new_duplicate_student_phone on public.students;
create trigger coachfit_reject_new_duplicate_student_phone
before insert or update of coach_id, phone on public.students
for each row execute function public.coachfit_reject_new_duplicate_student_phone();

-- The app subscription paid to Coach Fit Pro is independent from the professional's
-- own invoice field (students.payment). For affiliate professionals, only the
-- persisted app subscription state gates app tools.
create or replace function public.coachfit_student_financial_access_by_invite(p_invite_code text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.student_invites as invites
    join public.students as students
      on students.id = invites.student_id
     and students.coach_id = invites.coach_id
    where invites.code = trim(p_invite_code)
      and invites.status = 'active'
      and (invites.expires_at is null or invites.expires_at > now())
      and (
        not public.coachfit_professional_requires_app_payment(invites.coach_id)
        or (
          (
            students.app_payment_status = 'active'
            and (
              students.app_subscription_expires_at is null
              or students.app_subscription_expires_at > now()
            )
          )
          or students.access_override_until > now()
        )
      )
  );
$$;

revoke all on function public.coachfit_student_financial_access_by_invite(text) from public, anon, authenticated;

-- Direct payment links generated by the professional are only valid when the
-- professional belongs to the affiliate program.
create or replace function public.create_student_checkout_session(target_student_id uuid)
returns table (checkout_token uuid, student_id uuid, status text, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_session public.student_checkout_sessions%rowtype;
  v_user public.users%rowtype;
  v_invite public.student_invites%rowtype;
  v_affiliate_email text;
  v_professional_type text;
begin
  if auth.uid() is null then
    raise exception 'Sessao expirada' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.students as students
    where students.id = target_student_id
      and students.coach_id = auth.uid()
  ) then
    raise exception 'Aluno nao pertence ao profissional autenticado' using errcode = '42501';
  end if;

  if not public.coachfit_professional_requires_app_payment(auth.uid()) then
    raise exception 'Este profissional nao participa da cobranca por aluno/paciente.'
      using errcode = '42501';
  end if;

  select * into v_user
  from public.users
  where id = auth.uid();

  v_affiliate_email := lower(btrim(v_user.email));
  v_professional_type := case
    when lower(coalesce(v_user.role, '')) like '%nutri%' then 'nutritionist'
    else 'trainer'
  end;

  select * into v_invite
  from public.student_invites
  where coach_id = auth.uid()
    and student_id = target_student_id
    and status = 'active'
    and (expires_at is null or expires_at > now())
  order by created_at desc
  limit 1;

  update public.student_checkout_sessions as checkout_sessions
  set status = 'canceled', updated_at = now()
  where checkout_sessions.coach_id = auth.uid()
    and checkout_sessions.student_id = target_student_id
    and checkout_sessions.status = 'pending';

  insert into public.student_checkout_sessions (
    coach_id,
    student_id,
    source_invite_id,
    affiliate_email_snapshot,
    professional_type_snapshot,
    offer_code
  )
  values (
    auth.uid(),
    target_student_id,
    v_invite.id,
    v_affiliate_email,
    v_professional_type,
    case when v_professional_type = 'nutritionist'
      then 'patient_monthly_25_v1'
      else 'student_monthly_25_v1'
    end
  )
  returning * into new_session;

  return query
  select new_session.checkout_token, new_session.student_id, new_session.status, new_session.expires_at;
end;
$$;

revoke all on function public.create_student_checkout_session(uuid) from public, anon;
grant execute on function public.create_student_checkout_session(uuid) to authenticated;

-- Anonymous invite checkout preserves the attribution snapshot in the backend.
create or replace function public.create_student_checkout_session_by_invite(invite_code text)
returns table (checkout_token uuid, status text, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  active_invite public.student_invites%rowtype;
  new_session public.student_checkout_sessions%rowtype;
  v_user public.users%rowtype;
  v_professional_type text;
begin
  select invites.* into active_invite
  from public.student_invites as invites
  join public.students as students
    on students.id = invites.student_id
   and students.coach_id = invites.coach_id
  where invites.code = trim(invite_code)
    and invites.status = 'active'
    and (invites.expires_at is null or invites.expires_at > now())
  order by invites.created_at desc
  limit 1;

  if active_invite.id is null then
    raise exception 'Convite nao encontrado ou expirado' using errcode = '42501';
  end if;

  if not public.coachfit_professional_requires_app_payment(active_invite.coach_id) then
    raise exception 'Este profissional nao exige pagamento do aplicativo.'
      using errcode = '42501';
  end if;

  select * into v_user
  from public.users
  where id = active_invite.coach_id;

  v_professional_type := case
    when lower(coalesce(v_user.role, '')) like '%nutri%' then 'nutritionist'
    else 'trainer'
  end;

  update public.student_checkout_sessions as sessions
  set status = 'canceled', updated_at = now()
  where sessions.coach_id = active_invite.coach_id
    and sessions.student_id = active_invite.student_id
    and sessions.status = 'pending';

  insert into public.student_checkout_sessions (
    coach_id,
    student_id,
    source_invite_id,
    affiliate_email_snapshot,
    professional_type_snapshot,
    offer_code
  )
  values (
    active_invite.coach_id,
    active_invite.student_id,
    active_invite.id,
    lower(btrim(v_user.email)),
    v_professional_type,
    case when v_professional_type = 'nutritionist'
      then 'patient_monthly_25_v1'
      else 'student_monthly_25_v1'
    end
  )
  returning * into new_session;

  return query
  select new_session.checkout_token, new_session.status, new_session.expires_at;
end;
$$;

revoke all on function public.create_student_checkout_session_by_invite(text) from public;
grant execute on function public.create_student_checkout_session_by_invite(text) to anon, authenticated;

-- Atomic webhook processor for affiliate student/patient purchases.
-- Only the service role used by the Edge Function can invoke it.
create or replace function public.process_cartpanda_student_payment_event(
  p_event_id text,
  p_event_type text,
  p_correlation_id text,
  p_buyer_email text,
  p_provider_order_id text,
  p_provider_subscription_id text,
  p_product_id text,
  p_product_name text,
  p_amount_cents integer,
  p_status text,
  p_confirmed_payment boolean,
  p_provider_event_at timestamptz,
  p_period_ends_at timestamptz,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event public.payment_webhook_events%rowtype;
  v_session public.student_checkout_sessions%rowtype;
  v_student public.students%rowtype;
  v_effective_status text;
  v_event_at timestamptz := coalesce(p_provider_event_at, now());
  v_rank integer;
  v_affiliate_email text;
  v_existing_payment public.affiliate_student_payments%rowtype;
  v_period_end timestamptz;
  v_now timestamptz := now();
begin
  if nullif(btrim(p_event_id), '') is null then
    raise exception 'event_id obrigatorio' using errcode = '22023';
  end if;

  if p_status not in ('pending', 'active', 'past_due', 'canceled', 'refunded', 'chargeback') then
    raise exception 'status de pagamento invalido' using errcode = '22023';
  end if;

  -- Serialize exact replays before doing any state transition.
  perform pg_advisory_xact_lock(hashtextextended(p_event_id, 0));

  insert into public.payment_webhook_events (
    provider,
    event_id,
    event_type,
    buyer_email,
    provider_order_id,
    provider_subscription_id,
    product_id,
    product_name,
    amount_cents,
    subscription_status,
    processed,
    processing_error,
    payload,
    provider_event_at
  )
  values (
    'cartpanda',
    p_event_id,
    nullif(p_event_type, ''),
    nullif(lower(btrim(p_buyer_email)), ''),
    nullif(p_provider_order_id, ''),
    nullif(p_provider_subscription_id, ''),
    nullif(p_product_id, ''),
    nullif(p_product_name, ''),
    p_amount_cents,
    p_status,
    false,
    null,
    coalesce(p_payload, '{}'::jsonb),
    v_event_at
  )
  on conflict (event_id) do nothing;

  select * into v_event
  from public.payment_webhook_events
  where event_id = p_event_id
  for update;

  if v_event.processed then
    return jsonb_build_object(
      'ok', true,
      'processed', true,
      'reason', 'duplicate_event'
    );
  end if;

  if nullif(p_correlation_id, '') is not null
     and p_correlation_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    select * into v_session
    from public.student_checkout_sessions
    where checkout_token = p_correlation_id::uuid
    limit 1
    for update;
  elsif nullif(p_provider_subscription_id, '') is not null then
    select * into v_session
    from public.student_checkout_sessions
    where provider_subscription_id = p_provider_subscription_id
    order by created_at desc
    limit 1
    for update;
  end if;

  if v_session.id is null then
    update public.payment_webhook_events
    set processing_error = 'student_checkout_not_found'
    where event_id = p_event_id;

    return jsonb_build_object(
      'ok', true,
      'processed', false,
      'reason', 'student_checkout_not_found'
    );
  end if;

  -- The purchased product is contractually R$25.00/month.
  -- Reject a confirmed activation if CartPanda reports a different or missing amount.
  if p_status = 'active' and p_confirmed_payment
     and coalesce(p_amount_cents, -1) <> 2500 then
    update public.payment_webhook_events
    set processed = true,
        processing_error = 'unexpected_student_amount'
    where event_id = p_event_id;

    return jsonb_build_object(
      'ok', false,
      'processed', true,
      'reason', 'unexpected_student_amount',
      'status', 'pending'
    );
  end if;

  v_effective_status := case
    when p_status = 'active' and not p_confirmed_payment then 'pending'
    else p_status
  end;

  v_rank := case v_effective_status
    when 'chargeback' then 60
    when 'refunded' then 50
    when 'canceled' then 40
    when 'past_due' then 30
    when 'active' then 20
    else 10
  end;

  -- Ignore stale/out-of-order provider events. Same-timestamp terminal states win.
  if v_session.last_provider_event_at is not null
     and (
       v_event_at < v_session.last_provider_event_at
       or (
         v_event_at = v_session.last_provider_event_at
         and v_rank < v_session.last_provider_event_rank
       )
     ) then
    update public.payment_webhook_events
    set processed = true,
        processing_error = 'stale_event_ignored'
    where event_id = p_event_id;

    return jsonb_build_object(
      'ok', true,
      'processed', true,
      'reason', 'stale_event_ignored',
      'studentId', v_session.student_id,
      'coachId', v_session.coach_id
    );
  end if;

  select * into v_student
  from public.students
  where id = v_session.student_id
    and coach_id = v_session.coach_id
  for update;

  if v_student.id is null then
    update public.payment_webhook_events
    set processing_error = 'student_not_found'
    where event_id = p_event_id;

    return jsonb_build_object(
      'ok', true,
      'processed', false,
      'reason', 'student_not_found'
    );
  end if;

  if nullif(v_session.affiliate_email_snapshot, '') is null then
    select lower(btrim(users.email)) into v_affiliate_email
    from public.users as users
    join public.affiliate_professionals as affiliates
      on affiliates.email = lower(btrim(users.email))
     and affiliates.active = true
    where users.id = v_session.coach_id;

    if v_affiliate_email is not null then
      update public.student_checkout_sessions
      set affiliate_email_snapshot = v_affiliate_email
      where id = v_session.id;
      v_session.affiliate_email_snapshot := v_affiliate_email;
    end if;
  end if;

  update public.student_checkout_sessions
  set
    status = v_effective_status,
    buyer_email = nullif(lower(btrim(p_buyer_email)), ''),
    provider_order_id = coalesce(nullif(p_provider_order_id, ''), provider_order_id),
    provider_subscription_id = coalesce(nullif(p_provider_subscription_id, ''), provider_subscription_id),
    amount_cents = coalesce(p_amount_cents, amount_cents),
    paid_at = case when v_effective_status = 'active' then v_event_at else paid_at end,
    last_provider_event_at = v_event_at,
    last_provider_event_id = p_event_id,
    last_provider_event_rank = v_rank,
    updated_at = v_now
  where id = v_session.id;

  if v_effective_status = 'active' then
    v_period_end := case
      when p_period_ends_at is not null and p_period_ends_at > v_event_at then p_period_ends_at
      else (v_event_at + interval '1 month')
    end;

    update public.students
    set
      app_payment_status = 'active',
      app_subscription_started_at = coalesce(app_subscription_started_at, v_event_at),
      app_subscription_expires_at = greatest(
        coalesce(app_subscription_expires_at, '-infinity'::timestamptz),
        v_period_end
      ),
      updated_at = v_now
    where id = v_session.student_id
      and coach_id = v_session.coach_id;

    v_affiliate_email := nullif(lower(btrim(v_session.affiliate_email_snapshot)), '');

    if v_affiliate_email is not null then
      insert into public.affiliate_student_payments (
        webhook_event_id,
        coach_id,
        student_id,
        affiliate_email,
        status,
        paid_at,
        payment_month,
        revenue_cents,
        provider_amount_cents,
        commission_rate,
        commission_cents,
        provider,
        provider_order_id,
        provider_subscription_id,
        updated_at
      )
      values (
        p_event_id,
        v_session.coach_id,
        v_session.student_id,
        v_affiliate_email,
        'paid',
        v_event_at,
        date_trunc('month', v_event_at)::date,
        2500,
        p_amount_cents,
        0.2500,
        625,
        'cartpanda',
        nullif(p_provider_order_id, ''),
        nullif(p_provider_subscription_id, ''),
        v_now
      )
      on conflict (webhook_event_id) do nothing;
    end if;

  elsif v_effective_status in ('refunded', 'chargeback') then
    update public.students
    set
      app_payment_status = v_effective_status,
      updated_at = v_now
    where id = v_session.student_id
      and coach_id = v_session.coach_id;

    select * into v_existing_payment
    from public.affiliate_student_payments as payments
    where payments.coach_id = v_session.coach_id
      and payments.student_id = v_session.student_id
      and payments.status = 'paid'
      and (
        (
          nullif(p_provider_order_id, '') is not null
          and payments.provider_order_id = p_provider_order_id
        )
        or (
          nullif(p_provider_order_id, '') is null
          and nullif(p_provider_subscription_id, '') is not null
          and payments.provider_subscription_id = p_provider_subscription_id
        )
      )
    order by payments.paid_at desc
    limit 1
    for update;

    if v_existing_payment.id is not null then
      update public.affiliate_student_payments
      set
        status = v_effective_status,
        reversal_event_id = p_event_id,
        reversed_at = v_event_at,
        updated_at = v_now
      where id = v_existing_payment.id;
    end if;

  elsif v_effective_status in ('past_due', 'canceled') then
    update public.students
    set
      app_payment_status = v_effective_status,
      updated_at = v_now
    where id = v_session.student_id
      and coach_id = v_session.coach_id;

  elsif v_effective_status = 'pending' then
    -- A pending renewal must not revoke a still-current paid period.
    if v_student.app_payment_status <> 'active'
       or v_student.app_subscription_expires_at is null
       or v_student.app_subscription_expires_at <= v_now then
      update public.students
      set app_payment_status = 'pending', updated_at = v_now
      where id = v_session.student_id
        and coach_id = v_session.coach_id;
    end if;
  end if;

  update public.payment_webhook_events
  set
    processed = true,
    processing_error = null,
    subscription_status = v_effective_status,
    provider_event_at = v_event_at
  where event_id = p_event_id;

  return jsonb_build_object(
    'ok', true,
    'processed', true,
    'reason', 'processed',
    'studentId', v_session.student_id,
    'coachId', v_session.coach_id,
    'status', v_effective_status
  );
end;
$$;

revoke all on function public.process_cartpanda_student_payment_event(
  text,text,text,text,text,text,text,text,integer,text,boolean,timestamptz,timestamptz,jsonb
) from public, anon, authenticated;
grant execute on function public.process_cartpanda_student_payment_event(
  text,text,text,text,text,text,text,text,integer,text,boolean,timestamptz,timestamptz,jsonb
) to service_role;

-- Raw webhook payloads must never be exposed to anonymous/signed-in API clients.
alter view public.cartpanda_webhook_events set (security_invoker = true);
revoke all on public.cartpanda_webhook_events from public, anon, authenticated;
grant select on public.cartpanda_webhook_events to service_role;

-- Trigger functions are not public RPC endpoints.
revoke all on function public.create_coach_subscription() from public, anon, authenticated;


-- Read-only affiliate summary for the authenticated trainer/nutritionist.
create or replace function public.get_my_affiliate_report(
  p_start_date date default date_trunc('month', current_date)::date,
  p_end_date date default current_date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $
declare
  v_start date := coalesce(p_start_date, date_trunc('month', current_date)::date);
  v_end date := coalesce(p_end_date, current_date);
  v_email text;
  v_result jsonb;
begin
  if auth.uid() is null then
    raise exception 'Sessao expirada' using errcode = '42501';
  end if;

  if v_start > v_end or (v_end - v_start) > 1095 then
    raise exception 'Periodo invalido' using errcode = '22007';
  end if;

  select lower(btrim(users.email)) into v_email
  from public.users as users
  where users.id = auth.uid();

  if v_email is null or not exists (
    select 1
    from public.affiliate_professionals as affiliates
    where affiliates.email = v_email
      and affiliates.active = true
  ) then
    return null;
  end if;

  select jsonb_build_object(
    'startDate', v_start,
    'endDate', v_end,
    'studentsBrought', (
      select count(*)::int
      from public.students as students
      where students.coach_id = auth.uid()
    ),
    'activeClients', (
      select count(*)::int
      from public.students as students
      where students.coach_id = auth.uid()
        and students.app_payment_status = 'active'
        and (
          students.app_subscription_expires_at is null
          or students.app_subscription_expires_at > now()
        )
    ),
    'paidClients', (
      select count(distinct payments.student_id)::int
      from public.affiliate_student_payments as payments
      where payments.coach_id = auth.uid()
        and payments.affiliate_email = v_email
        and payments.status = 'paid'
        and payments.paid_at >= v_start::timestamptz
        and payments.paid_at < (v_end + 1)::timestamptz
    ),
    'paidInstallments', (
      select count(*)::int
      from public.affiliate_student_payments as payments
      where payments.coach_id = auth.uid()
        and payments.affiliate_email = v_email
        and payments.status = 'paid'
        and payments.paid_at >= v_start::timestamptz
        and payments.paid_at < (v_end + 1)::timestamptz
    ),
    'revenueCents', (
      select coalesce(sum(payments.revenue_cents), 0)::int
      from public.affiliate_student_payments as payments
      where payments.coach_id = auth.uid()
        and payments.affiliate_email = v_email
        and payments.status = 'paid'
        and payments.paid_at >= v_start::timestamptz
        and payments.paid_at < (v_end + 1)::timestamptz
    ),
    'commissionCents', (
      select coalesce(sum(payments.commission_cents), 0)::int
      from public.affiliate_student_payments as payments
      where payments.coach_id = auth.uid()
        and payments.affiliate_email = v_email
        and payments.status = 'paid'
        and payments.paid_at >= v_start::timestamptz
        and payments.paid_at < (v_end + 1)::timestamptz
    ),
    'sales', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'paymentId', payments.id,
          'studentId', payments.student_id,
          'clientName', coalesce(nullif(btrim(students.name), ''), 'Aluno/Paciente'),
          'paidAt', payments.paid_at,
          'revenueCents', payments.revenue_cents,
          'commissionCents', payments.commission_cents,
          'status', payments.status,
          'offerCode', sessions.offer_code
        )
        order by payments.paid_at desc
      )
      from public.affiliate_student_payments as payments
      left join public.students as students
        on students.id = payments.student_id
       and students.coach_id = auth.uid()
      left join public.student_checkout_sessions as sessions
        on sessions.coach_id = payments.coach_id
       and sessions.student_id = payments.student_id
       and (
         sessions.provider_order_id = payments.provider_order_id
         or (
           sessions.provider_order_id is null
           and sessions.provider_subscription_id = payments.provider_subscription_id
         )
       )
      where payments.coach_id = auth.uid()
        and payments.affiliate_email = v_email
        and payments.paid_at >= v_start::timestamptz
        and payments.paid_at < (v_end + 1)::timestamptz
    ), '[]'::jsonb)
  )
  into v_result;

  return v_result;
end;
$;

revoke all on function public.get_my_affiliate_report(date, date) from public, anon;
grant execute on function public.get_my_affiliate_report(date, date) to authenticated;

commit;
