export const coachfitMediaAliases = Object.freeze({
  'supino reto com barra': ['barbell bench press medium grip'],
  'supino inclinado com halteres': ['incline dumbbell press'],
  'crucifixo com halteres': ['dumbbell flyes'],
  'flexao de bracos': ['pushups'],
  'puxada frontal': ['wide grip lat pulldown'],
  'remada baixa': ['seated cable rows'],
  'remada curvada com barra': ['bent over barbell row'],
  'barra fixa': ['pullups'],
  'desenvolvimento com halteres': ['dumbbell shoulder press'],
  'elevacao lateral': ['side lateral raise'],
  'rosca direta': ['barbell curl'],
  'rosca direta com barra': ['barbell curl'],
  'rosca alternada': ['dumbbell alternate bicep curl'],
  'triceps na polia': ['triceps pushdown'],
  'triceps frances': ['standing dumbbell triceps extension'],
  'agachamento livre': ['barbell squat'],
  'leg press 45': ['leg press'],
  'cadeira extensora': ['leg extensions'],
  'mesa flexora': ['lying leg curls'],
  'stiff com barra': ['romanian deadlift'],
  'levantamento terra': ['barbell deadlift'],
  'afundo com halteres': ['dumbbell lunges'],
  'elevacao pelvica': ['barbell hip thrust'],
  'panturrilha em pe': ['standing calf raises'],
  'prancha abdominal': ['plank'],
  'abdominal crunch': ['crunches'],
})

export default coachfitMediaAliases
